# Section A: Data Structures & Control Structures



# 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [ ]:
l = [15,35,45,65,75]
l.append(75)
print('after append:', l)
l.extend([12,23,45])
print('after extend:', l)
l.insert(4, 2.56)
print('after insert:', l)

after append: [15, 35, 45, 65, 75, 75]
after extend: [15, 35, 45, 65, 75, 75, 12, 23, 45]
after insert: [15, 35, 45, 65, 2.56, 75, 75, 12, 23, 45]


In [ ]:
l.remove(35)
print(l)

[15, 45, 65, 2.56, 75, 75, 12, 23, 45]


In [ ]:
l.pop()
print(l)

[15, 45, 65, 2.56, 75, 75, 12, 23]


In [ ]:
l.index(12)

6

In [ ]:
l.count(75)

2

In [ ]:
l.sort()
print(l)

[2.56, 12, 15, 23, 45, 65, 75, 75]


In [ ]:
l.sort(reverse = True)
print(l)

[75, 75, 65, 45, 23, 15, 12, 2.56]


# 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [ ]:
t= ('Divya','Deepika','Kavya')
print(t)

('Divya', 'Deepika', 'Kavya')


In [ ]:
t[2] = 'Yuvan'
print(t)
#Here the element or name does not change because tuple cannot be changed it is immutable once created

TypeError: 'tuple' object does not support item assignment


# 3.	Create a set of integers with some duplicate values. Print the set and explain the output.


In [ ]:
set = {4,6,8,3,9,4,5,6,20,45}
print(set)
# Explaination: Set naturally removes the duplicate value and keeps only unique value and also order is not defined, like in list index specification is not applicable in set

{3, 4, 5, 6, 8, 9, 45, 20}


# 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.


In [ ]:
d = {'Name': 'Divya', 'Age': 36, 'City': 'Bengaluru'}
print(d)

{'Name': 'Divya', 'Age': 36, 'City': 'Bengaluru'}


In [ ]:
d['Age']= 37
print(d)

{'Name': 'Divya', 'Age': 37, 'City': 'Bengaluru'}


In [ ]:
d['Email'] = 'divyapragati@gmail.com'
print(d)

{'Name': 'Divya', 'Age': 37, 'City': 'Bengaluru', 'Email': 'divyapragati@gmail.com'}


5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.


In [ ]:
age= int(input('Enter age:'))
if age >= 18:
  print('Eligible to vote')
else:
  print('Not eligible to vote')


Enter age:35
Eligible to vote


6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [ ]:
marks = int(input('Enter marks:'))
if marks >=90:
  print('A')
elif marks >=75 and marks >=89:
  print('B')
elif marks >=50 and marks >=74:
  print('C')
else:
  print('Fail')

Enter marks:35
Fail


7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [ ]:
num = int(input('Enter a number:'))
if num > 0:
  if num % 2 == 0:
    print('Positive and even')
  else:
    print('Positive and odd')
elif num == 0:
  print('Zero')
else:
  print('Negative')

Enter a number:-6
Negative


#Section B: Numpy
8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10



In [ ]:
import numpy as np
import pandas as pd

In [ ]:
x = np.array(5)
print(x)
x.ndim

5


0

In [ ]:
y = np.array([1,2,3,4,5])
print(y)
y.ndim

[1 2 3 4 5]


1

In [ ]:
z = np.array([[10, 20, 30] , [40, 50, 60]])
print(z)
z.ndim

[[10 20 30]
 [40 50 60]]


2

9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().


In [ ]:
r = np.random.randint(0,101,(4,4))
print(r)

[[35 31 93 13]
 [28 77 98 59]
 [13 54 69 99]
 [ 3 41 26 30]]


10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [ ]:
z = np.array([[10, 20, 30] , [40, 50, 60], [70, 80, 90]])
print(z)
z.ndim

[[10 20 30]
 [40 50 60]
 [70 80 90]]


2

In [ ]:
df= pd.DataFrame(z, columns= ['A','B','C'])
df

,A,B,C
0,10,20,30
1,40,50,60
2,70,80,90


# Section C: Exploring Pandas
11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [ ]:
import pandas as pd

In [ ]:
data = {'Name': ['Divya', 'Deepika','Kavya','Yuvan','Arihant','Kshirav','Shantha','Gopala','Shiva','Purushutham'],
        'Age': [37,37,34,7,4,1,56,76,35,42],
        'City' : ['Bangalore', 'Chennai','Pondicherry', 'Hyderabad','Mumbai', 'Delhi', 'jaisalmair', 'Odissa', 'Ahmedabad', 'Panji'],
        'Salary': [23000, 34000, 45000, 65000, None, None , 67000, 84000, 120000, 95000]}

In [ ]:
df = pd.DataFrame(data)
df

,Name,Age,City,Salary
0,Divya,37,Bangalore,23000.0
1,Deepika,37,Chennai,34000.0
2,Kavya,34,Pondicherry,45000.0
3,Yuvan,7,Hyderabad,65000.0
4,Arihant,4,Mumbai,NaN
5,Kshirav,1,Delhi,NaN
6,Shantha,56,jaisalmair,67000.0
7,Gopala,76,Odissa,84000.0
8,Shiva,35,Ahmedabad,120000.0
9,Purushutham,42,Panji,95000.0


In [ ]:
df = pd.DataFrame(data, index= range(1,11))
df

,Name,Age,City,Salary
1,Divya,37,Bangalore,23000.0
2,Deepika,37,Chennai,34000.0
3,Kavya,34,Pondicherry,45000.0
4,Yuvan,7,Hyderabad,65000.0
5,Arihant,4,Mumbai,NaN
6,Kshirav,1,Delhi,NaN
7,Shantha,56,jaisalmair,67000.0
8,Gopala,76,Odissa,84000.0
9,Shiva,35,Ahmedabad,120000.0
10,Purushutham,42,Panji,95000.0


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 1 to 10
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [ ]:
df.describe()

,Age,Salary
count,10.00000,8.000000
mean,32.90000,66625.000000
std,23.65704,32500.274724
min,1.00000,23000.000000
25%,13.75000,42250.000000
50%,36.00000,66000.000000
75%,40.75000,86750.000000
max,76.00000,120000.000000


In [ ]:
df[['Name','City']]

,Name,City
1,Divya,Bangalore
2,Deepika,Chennai
3,Kavya,Pondicherry
4,Yuvan,Hyderabad
5,Arihant,Mumbai
6,Kshirav,Delhi
7,Shantha,jaisalmair
8,Gopala,Odissa
9,Shiva,Ahmedabad
10,Purushutham,Panji


In [ ]:
df1= df.drop('City', axis = 1)
df1

,Name,Age,Salary
1,Divya,37,23000.0
2,Deepika,37,34000.0
3,Kavya,34,45000.0
4,Yuvan,7,65000.0
5,Arihant,4,NaN
6,Kshirav,1,NaN
7,Shantha,56,67000.0
8,Gopala,76,84000.0
9,Shiva,35,120000.0
10,Purushutham,42,95000.0


In [ ]:
df

,Name,Age,City,Salary
1,Divya,37,Bangalore,23000.0
2,Deepika,37,Chennai,34000.0
3,Kavya,34,Pondicherry,45000.0
4,Yuvan,7,Hyderabad,65000.0
5,Arihant,4,Mumbai,NaN
6,Kshirav,1,Delhi,NaN
7,Shantha,56,jaisalmair,67000.0
8,Gopala,76,Odissa,84000.0
9,Shiva,35,Ahmedabad,120000.0
10,Purushutham,42,Panji,95000.0


In [ ]:
df.isnull().sum()

,0
Name,0
Age,0
City,0
Salary,2


In [ ]:
df['Salary'].fillna(df['Salary'].mean(), inplace = True)
df

/tmp/ipykernel_19698/3912328046.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(), inplace = True)


,Name,Age,City,Salary
1,Divya,37,Bangalore,23000.0
2,Deepika,37,Chennai,34000.0
3,Kavya,34,Pondicherry,45000.0
4,Yuvan,7,Hyderabad,65000.0
5,Arihant,4,Mumbai,66625.0
6,Kshirav,1,Delhi,66625.0
7,Shantha,56,jaisalmair,67000.0
8,Gopala,76,Odissa,84000.0
9,Shiva,35,Ahmedabad,120000.0
10,Purushutham,42,Panji,95000.0


In [ ]:
df.isnull().sum()

,0
Name,0
Age,0
City,0
Salary,0


In [ ]:
df.duplicated().sum()

np.int64(0)